In [ ]:
import pandas as pd
import numpy as np

from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [ ]:
df1 = pd.read_csv('/content/gdrive/MyDrive/data/P230604-01.csv')

In [ ]:
df2 = pd.read_csv('/content/gdrive/MyDrive/data/P230604-02.csv')

In [ ]:
df1['price_range']=df1['price_range'].astype('category')
df1['blue']=df1['blue'].astype('category')
df1['dual_sim']=df1['dual_sim'].astype('category')
df1['four_g']=df1['four_g'].astype('category')
df1['n_cores']=df1['n_cores'].astype('category')
df1['three_g']=df1['three_g'].astype('category')
df1['touch_screen']=df1['touch_screen'].astype('category')
df1['wifi']=df1['wifi'].astype('category')

In [ ]:
df2['blue']=df2['blue'].astype('category')
df2['dual_sim']=df2['dual_sim'].astype('category')
df2['four_g']=df2['four_g'].astype('category')
df2['n_cores']=df2['n_cores'].astype('category')
df2['three_g']=df2['three_g'].astype('category')
df2['touch_screen']=df2['touch_screen'].astype('category')
df2['wifi']=df2['wifi'].astype('category')

In [ ]:
md=RandomForestClassifier(n_estimators=300)

In [ ]:
x= df1.drop('price_range',axis= 1)
y = df1['price_range']

In [ ]:
x_encoded = pd.get_dummies(x)

In [ ]:
x_train,x_valid,y_train,y_valid = train_test_split(x_encoded,y,test_size = 0.25, random_state = 42)

In [ ]:
md.fit(x_train,y_train)

RandomForestClassifier(n_estimators=300)

In [ ]:
pred = md.predict(x_valid)

In [ ]:
cm = confusion_matrix(y_valid,pred)
print(cm)

[[126   6   0   0]
 [ 12  97   9   0]
 [  0  14  94  12]
 [  0   0  14 116]]


In [ ]:
print(accuracy_score(y_valid,pred))

0.866


In [ ]:
x_test = df2

In [ ]:
x_test_encoded = pd.get_dummies(x_test)

In [ ]:
md=RandomForestClassifier(n_estimators=300)

In [ ]:
md.fit(x_encoded,y)

RandomForestClassifier(n_estimators=300)

In [ ]:
result = pd.DataFrame({'pred':pred})
print(result)

     pred
0       0
1       2
2       0
3       3
4       1
..    ...
495     0
496     1
497     2
498     3
499     1

[500 rows x 1 columns]


[0 2 0 3 1 2 2 0 3 1 0 0 2 3 2 2 3 3 1 0 0 1 1 2 0 1 2 2 2 0 0 0 3 0 1 1 2
 0 3 0 2 3 2 0 3 2 1 1 3 1 3 1 0 0 1 1 1 2 0 0 0 3 3 2 0 0 3 3 2 2 2 3 0 1
 2 0 0 3 2 2 3 2 1 0 1 3 1 3 3 0 3 3 2 1 3 2 2 3 2 1 0 0 1 0 0 3 2 0 1 1 0
 0 3 1 2 2 3 3 0 2 1 3 2 1 3 3 0 3 0 2 3 0 2 2 0 3 1 0 0 2 3 0 2 2 0 0 0 1
 1 2 3 1 1 0 2 2 0 1 0 1 2 3 3 2 1 0 0 2 2 3 3 1 0 0 3 1 2 2 1 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 3 1 0 1 2 1 1 2 2 2 3 3 1 3 0 0 0 2 1 1 3 1 0 2 1 1 3 1
 3 0 0 2 1 2 0 0 2 0 1 3 2 0 1 2 3 0 1 3 3 3 0 3 1 2 3 3 2 1 1 3 3 1 3 3 3
 3 3 0 1 2 2 2 2 0 2 3 2 2 2 1 0 2 0 3 3 1 3 1 0 3 1 2 0 0 3 0 1 2 3 3 3 1
 0 0 1 3 3 0 1 1 2 0 3 3 2 3 1 3 2 0 2 1 1 1 0 0 0 3 2 3 1 0 1 0 2 2 2 0 3
 3 2 1 2 0 0 3 1 3 2 0 1 1 2 1 1 3 1 0 0 3 3 0 3 0 0 1 0 0 2 2 2 3 0 3 2 2
 3 3 3 2 1 2 0 3 1 3 3 0 2 3 2 3 3 3 0 0 2 3 0 0 2 3 2 1 1 2 1 2 1 3 1 2 0
 0 1 0 1 0 2 0 2 2 3 2 1 1 3 1 0 3 1 0 0 3 0 1 0 0 1 3 3 0 2 1 1 1 3 3 1 2
 0 2 0 0 3 3 0 2 2 1 3 1 1 0 1 3 1 0 3 1 0 0 3 2 3 2 0 3 1 0 1 2 3 2 1 0 0
 1 2 2 1 1 1 3 1 2 0 3 2 