In [ ]:
import pandas as pd
import numpy as np

from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

In [ ]:
df = pd.read_csv('/content/gdrive/MyDrive/data/P220404-01.csv')

In [ ]:
df['Segmentation'] = df['Segmentation'].astype("category")

In [ ]:
df2 = pd.read_csv('/content/gdrive/MyDrive/data/P220404-02.csv')

In [ ]:
x = df.drop('Segmentation',axis =1 )
y = df['Segmentation']

In [ ]:
x_encoded = pd.get_dummies(x)

In [ ]:
x_train,x_valid,y_train,y_valid = train_test_split(x_encoded,y,test_size = 0.25, random_state = 42)

In [ ]:
md = RandomForestClassifier(n_estimators=300)
md.fit(x_train.drop('ID',axis=1),y_train)

RandomForestClassifier(n_estimators=300)

In [ ]:
pred = md.predict(x_valid.drop('ID',axis=1))

In [ ]:
cm = confusion_matrix(y_valid,pred,labels = ['A','B','C','D'])
print(cm)

[[181  74  67  79]
 [104 125 127  31]
 [ 55 105 215  52]
 [103  38  27 284]]


In [ ]:
print(accuracy_score(y_valid,pred))

0.4829034193161368


In [ ]:
x_test = df2
x_test_encoded = pd.get_dummies(x_test)

In [ ]:
md = RandomForestClassifier(n_estimators=300)

In [ ]:
md.fit(x_encoded.drop('ID',axis=1),y)

RandomForestClassifier(n_estimators=300)

In [ ]:
pred = md.predict(x_test_encoded.drop('ID',axis=1))

In [ ]:
result = pd.DataFrame({"ID":df2['ID'], "pred":pred})
print(result)

          ID pred
0     458989    B
1     458994    C
2     459000    C
3     459003    C
4     459005    A
...      ...  ...
2149  467950    A
2150  467954    D
2151  467958    B
2152  467961    C
2153  467968    D

[2154 rows x 2 columns]
